name: DevOps

on:
  push:
    branches:
      - main  # Varsayılan olarak "main" dalında değişiklik olduğunda tetiklenecek
  pull_request:
    branches:
      - main  # Pull request'ler "main" dalında açıldığında tetiklenecek

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/node@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
